package io.edukativ.myskoolin.domain.timetabling.constraints;
    dialect "java"

import io.edukativ.myskoolin.domain.timetabling.Lesson;
import io.edukativ.myskoolin.domain.subjects.Subject;
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;

global HardMediumSoftScoreHolder scoreHolder;

rule "Time slot overlapping another time slot"
    when
        $lesson1 : Lesson(timeSlot != null)
        $lesson2 : Lesson(timeSlot != null, $lesson1.isOverlapping($lesson2))
    then
        scoreHolder.penalize(kcontext, $lesson1.overlappingGap($lesson2));
end

rule "School room right type"
    when
        $lesson : Lesson(timeSlot != null)
        $subject : Subject(!schoolRoomsTypes.contains($lesson.schoolRoom.type))
    then
        scoreHolder.penalize(kcontext, 10);
end

