package io.edukativ.myskoolin.domain.timetabling.constraints;
    dialect "java"

import io.edukativ.myskoolin.domain.timetabling.Lesson;
import io.edukativ.myskoolin.domain.timetabling.TimeSlot;
import io.edukativ.myskoolin.domain.timetabling.SchoolClassTimeTable;
import io.edukativ.myskoolin.domain.subjects.Subject;
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;
import java.util.List

global HardMediumSoftScoreHolder scoreHolder;

rule "Time slot overlapping another time slot"
    when
        $lesson1 : Lesson(timeSlot != null)
        $lesson2 : Lesson(timeSlot != null, $lesson1.isOverlapping($lesson2))
    then
        scoreHolder.penalize(kcontext, $lesson1.overlappingGap($lesson2));
end

rule "School room right type"
    when
        $lesson: Lesson(!hasRightSchoolRoom())
    then
        scoreHolder.penalize(kcontext, $lesson.getTimeSlot().durationInMinutes().intValue());
end

//rule "Subject duration max by day"
//    when
//        $lesson : Lesson($subject : subject)
//        $subjectDurationTotal : Long() from accumulate(
//            Lesson(
//                $subject.equals(subject),
//                $subjectDuration : timeSlot.durationInMinutes()
//            ),
//            sum($subjectDuration)
//        )
//        Boolean($subject.getMaxMinutesPerDay() > $subjectDurationTotal)
//    then
//        System.out.println("----------------------$result : "+ ($subject.getMaxMinutesPerDay() > $subjectDurationTotal));
//        scoreHolder.penalize(kcontext, $subjectDurationTotal.intValue());
//end

//rule ""
//    when
//    then
//end
rule "Subject duration max by day"
    when
        $lesson1: Lesson($timeSlot1: timeSlot)
        accumulate(
            Lesson(subject.equals($lesson1.getSubject()),
                    $timeSlot1.day == timeSlot.day, $timeSlot2: timeSlot
            );
            $total : sum($timeSlot2.durationInMinutes());
            $total > $lesson1.subject.maxMinutesPerDay
        )
    then
        scoreHolder.penalize(kcontext, $total.intValue());
end
