package io.edukativ.myskoolin.domain.timetabling.constraints;
    dialect "java"

import io.edukativ.myskoolin.domain.timetabling.Lesson;
import io.edukativ.myskoolin.domain.timetabling.TimeSlot;
import io.edukativ.myskoolin.domain.timetabling.SchoolClassTimeTable;
import io.edukativ.myskoolin.domain.subjects.Subject;
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScoreHolder;
import java.util.List

global HardMediumSoftScoreHolder scoreHolder;

//----------------------------------------------------------------------------------------------------------

rule "Time slot overlapping another time slot"
    when
        $lesson1 : Lesson(timeSlot != null)
        $lesson2 : Lesson(timeSlot != null, $lesson1.isOverlapping($lesson2))
    then
        scoreHolder.penalize(kcontext, $lesson1.overlappingGap($lesson2));
end

//----------------------------------------------------------------------------------------------------------

rule "School room right type"
    when
        $lesson: Lesson(!hasRightSchoolRoom())
    then
        scoreHolder.penalize(kcontext, $lesson.getTimeSlot().durationInMinutes().intValue());
end

//----------------------------------------------------------------------------------------------------------

rule "Subject duration max by day"
    when
        $lesson : Lesson($subject1: subject)
        $subject2: Subject(equals($subject1))
        $total : Number() from accumulate(
                            Lesson(
                                timeSlot.day == $lesson.timeSlot.day,
                                subject.equals($subject1),
                                $value : timeSlot.durationInMinutes()
                            ),
                            sum( $value )
                          )
    then
        scoreHolder.penalize(kcontext, $total.intValue() - $subject1.getMaxMinutesPerDay());
end
