export enum Authorities {
    ROLE_ADMINISTRATION = 'ROLE_ADMINISTRATION',
    ROLE_INFIRMARY = 'ROLE_INFIRMARY',
    ROLE_SCHOOL_LIFE = 'ROLE_SCHOOL_LIFE',
    ROLE_SCHOOLME_ADMIN = 'ROLE_SCHOOLME_ADMIN',
    ROLE_STUDENTS = 'ROLE_STUDENTS',
    ROLE_STUDENT_RESPONSIBLE = 'ROLE_STUDENT_RESPONSIBLE',
    ROLE_TEACHERS = 'ROLE_TEACHERS',
    ROLE_ANONYMOUS = 'ROLE_ANONYMOUS'
}

export const AUTHORITIES_ALL = [
    Authorities.ROLE_ADMINISTRATION,
    Authorities.ROLE_INFIRMARY,
    Authorities.ROLE_SCHOOL_LIFE,
    Authorities.ROLE_SCHOOLME_ADMIN,
    Authorities.ROLE_STUDENTS,
    Authorities.ROLE_STUDENT_RESPONSIBLE,
    Authorities.ROLE_TEACHERS,
    Authorities.ROLE_ANONYMOUS
];

export const AUTHORITIES_AUTHENTICATED_USERS = [
    Authorities.ROLE_ADMINISTRATION,
    Authorities.ROLE_INFIRMARY,
    Authorities.ROLE_SCHOOL_LIFE,
    Authorities.ROLE_SCHOOLME_ADMIN,
    Authorities.ROLE_STUDENTS,
    Authorities.ROLE_STUDENT_RESPONSIBLE,
    Authorities.ROLE_TEACHERS
];

export const AUTHORITIES_ADMIN_USERS = [
    Authorities.ROLE_ADMINISTRATION,
    Authorities.ROLE_SCHOOL_LIFE,
    Authorities.ROLE_SCHOOLME_ADMIN
];
